name: Rogue Noise
favicon: null
layout_spectrum: 0
typography_spectrum: 0.35435
title: Rogue Noise Official Band Webstite
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d4e5ed'
    - '#9eb4c1'
    - '#050608'
    - '#394344'
    - '#758c92'
  brandStrength: 0.8125
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
