name: Rogue Noise
favicon: null
layout_spectrum: 0.51205
typography_spectrum: 0.22028
title: Rogue Noise Official Band Webstite
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d4e5ed'
    - '#9eb4c1'
    - '#050608'
    - '#394344'
    - '#758c92'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
