typography_spectrum: 0.22028
color:
  brandColors:
    - '#d4e5ed'
    - '#9eb4c1'
    - '#050608'
    - '#394344'
    - '#758c92'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.4375
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: Rogue Noise
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Music
    id: 7b68dcb2-6ade-488f-bdf8-25bceb88b2e6
    type: content
  - name: Booking
    id: fae270f9-a0c1-4bc3-9f2a-1076edd141df
    type: content
favicon: null
title: ''
description: The Official Band Website
purpose: []
