typography_spectrum: 0.3749670726247132
color:
  brandColors:
    - '#ECE978'
    - '#000000'
    - '#3A5F6B'
    - '#B1AF5A'
    - '#716F39'
  brandStrength: 0.09263339871540666
  lightness: 0.16524398676119745
  saturation: 0.256287271855399
  rhythmicContrast: 0.8932481093797833
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5710118988063186
analytics:
  google: UA-83534143-1
  facebook: null
  twitter: null
logo: null
name: Rogue Noise
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Music
    id: 7b68dcb2-6ade-488f-bdf8-25bceb88b2e6
    type: content
  - name: Booking
    id: fae270f9-a0c1-4bc3-9f2a-1076edd141df
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/36d60fce-13e9-439c-8dd0-f7bb8e22e888.jpg
title: ''
description: ''
purpose: []
